services:
  ollama-router:
    image: ollama-router:v0.0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ollama-router
    ports:
      - "5242:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Ollama__Servers__0=http://192.168.50.176:11434
      - Ollama__Servers__1=http://192.168.25.121:11434
      - Ollama__MaxConcurrentPerServer=2
    restart: unless-stopped
