services:
  ollama-router-web:
    image: ollama-router-web:v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-router-web
    ports:
      - "8080:80"
    restart: unless-stopped
